n = int(input("Digite um valor inteiro: "))
print("=" * 15)
print("{} * 1 = {}".format(n, n*1), "\n{} * 2 = {}".format(n, n*2)
      ,"\n{} * 3 = {}".format(n, n * 3), "\n{} * 4 = {}".format(n, n*4)
      ,"\n{} * 5 = {}".format(n, n*5), "\n{} * 6 = {}".format(n, n*6)
      ,"\n{} * 7 = {}".format(n, n*7), "\n{} * 8 = {}".format(n, n*8)
      ,"\n{} * 9 = {}".format(n, n*9), "\n{} * 10 = {}".format(n, n*10))
print("=" * 15)